[34m[1mwandb[39m[22m: [33mWARNING[39m Calling wandb.run.save without any arguments is deprecated.Changes to attributes are automatically persisted.
07/04/2024 18:45:56 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cuda
==> Preparing data..
07/04/2024 18:45:56 - INFO - __main__ - ==> Preparing data..
Traceback (most recent call last):
  File "finetune.py", line 150, in <module>
    main()
  File "finetune.py", line 107, in main
    datasets = get_dataset_eval(args.dataset_name, tokenizer=tokenizer, args=args)
  File "/home/0k9d0h1/piggyback/piggyback-ContinualLM/dataloader/data.py", line 580, in get_dataset_eval
    with open(os.path.join('../data/SemEval14-res', ds + '.json')) as f:
FileNotFoundError: [Errno 2] No such file or directory: '../data/SemEval14-res/train.json'